version: 3.0.{build}
image: Ubuntu2204
configuration: Release
branches:
   only:
      - main
      - /(release|task|feature|fix|hotfix|story)[/].*/

skip_tags: true

assembly_info:
   patch: true
   file: '**\AssemblyInfo.*'
   assembly_version: '{version}'
   assembly_file_version: '{version}'
   assembly_informational_version: '{version}-alpha'

dotnet_csproj:
   patch: true
   file: '**\*.csproj'
   version: '{version}'
   version_prefix: '{version}'
   package_version: '{version}-alpha'
   assembly_version: '{version}'
   file_version: '{version}'
   informational_version: '{version}-alpha'

environment:
   SONAR_TOKEN:
      secure: PHKmq/QK5apQjJA12j8uvP6FY9o2qAcGw7IzeyCsIdvVyamAHQos4fISdKQYOQvf

install:
- sh: >-
    #!/bin/bash
    
    sudo apt-get update && sudo apt-get install -y dotnet-sdk-8.0
    
    dotnet tool install --global dotnet-sonarscanner
build:
   publish_nuget: true
   publish_nuget_symbols: true
   use_snupkg_format: true
   verbosity: minimal

test_script:
- sh: >-   
    # sonar begin
     
    dotnet build-server shutdown
     
    if [[ -z "${APPVEYOR_PULL_REQUEST_NUMBER}" ]]; then
     
       dotnet sonarscanner begin /d:sonar.token="$SONAR_TOKEN" \
                                 /d:sonar.branch.name="$APPVEYOR_REPO_BRANCH"
     
    else
     
        dotnet sonarscanner begin /d:sonar.token="$SONAR_TOKEN" \
                                  /d:sonar.pullrequest.key="${APPVEYOR_PULL_REQUEST_NUMBER}"
     
    fi
    
    dotnet build --no-incremental -c Release
     
    # test
     
    dotnet test --collect:"XPlat Code Coverage;Format=opencover" --no-build  -c Release
     
    # sonar end
     
    dotnet sonarscanner end /d:sonar.token="$SONAR_TOKEN"
deploy:
- provider: NuGet
  server: https://www.myget.org/F/jason-c-daniels/api/v2/package
  api_key:
     secure: I8belHNTZOvJ4MZhZoH6bhQsVuAtAo/wvX2ypZENxIUJJJ+plfJ6pz2SJr8dlgEA
  symbol_server: https://www.myget.org/F/jason-c-daniels/api/v2/package
  on:
     branch: /^(main|release[/].*)$/

notifications:
- provider: Email
  to:
     - jason.c.daniels@gmail.com
  subject: Build failure - Jcd.BitManipulation {version}
  message: Build failure - Jcd.BitManipulation {version}
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false