title: Jcd.BitManipulation
logo: assets/img/logo.jpg
description: A .Net Standard 2.0 library adding syntactic sugar to your bit manipulation experience. 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal